name = "impackta-dashboard-envios"
main = "worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BAJAS_KV"
id = "51af001552ed4fcab781fa837127ea7d"
